name: Build and deploy to DockerHub

on:
  push:
    branches:
      - master

# Specify jobs
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
        - { image_name: ubuntu-build, dockerfile: ubuntu.Dockerfile }
    steps:
      - uses: actions/checkout@master
      - name: Login, build and push image
        if: success()
        uses: whoan/docker-build-with-cache-action@v4
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: "genrl/${{matrix.config.image_name}}"
          dockerfile: "docker/${{matrix.config.dockerfile}}"
          push_image_and_stages: true
